import Head from 'next/head';
import Banner from '../components/banner/banner.component';
import CardSections from '../components/card/card-sections.component';
import Card from '../components/card/card.component';
import NavBar from '../components/nav/navbar.component';
import styles from '../styles/Home.module.css';

export default function Home() {
  const dcMovies = [
    {
      imageUrl: '/static/the_flash.webp',
    },
    {
      imageUrl: '/static/the_flash.webp',
    },
    {
      imageUrl: '/static/the_flash.webp',
    },
  ];

  return (
    <div className={styles.container}>
      <Head>
        <title>Netflix</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <NavBar username='Ty@nextflix.io' />
      <Banner
        title='The Flash'
        subTitle='fastest superhero ever'
        imageUrl='/static/the_flash.webp'
      />
      <div className={styles.sectionsContainer}>
        <CardSections title='DC' movies={dcMovies} size='large' />
        <CardSections title='DC' movies={dcMovies} size='medium' />
      </div>
    </div>
  );
}
